# Generated by Django 5.1.6 on 2025-04-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20250412_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3personelatama',
            name='coffee_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t3personelveriler',
            name='coffee_break',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
