# Generated by Django 4.2.7 on 2025-04-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_sistemayarlari_t3personelatama_coffee_break_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anahtar', models.CharField(max_length=50, unique=True)),
                ('deger', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
            },
        ),
        migrations.AlterField(
            model_name='gonulludurumveriler',
            name='gun',
            field=models.CharField(max_length=50),
        ),
    ]
