# Generated by Django 4.2.7 on 2025-04-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_sistemayarlari_alter_gonulludurumveriler_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonulludurumveriler',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
