# Generated by Django 4.2.7 on 2025-04-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_gonulludurumveriler_fotograf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonullusorunveriler',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
