# Generated by Django 4.2.7 on 2025-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_gonullusorunveriler_fotograf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonullusorunveriler',
            name='gun',
            field=models.CharField(max_length=50),
        ),
    ]
