# Generated by Django 4.2.7 on 2025-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_gonullusorunveriler_gun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gonulludurumveriler',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='gonulludurumveriler',
            name='catering_durum',
            field=models.CharField(choices=[('var', 'Catering Var'), ('yok', 'Catering Yok')], default='yok', max_length=10),
        ),
        migrations.AddField(
            model_name='gonulludurumveriler',
            name='catering_urunleri',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
