# Generated by Django 5.1.6 on 2025-04-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_gonulludurumveriler_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonullusorunveriler',
            name='sorun_seviyesi',
            field=models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Acil', 'Acil')], default='Düşük', max_length=20),
        ),
        migrations.AddField(
            model_name='gonullusorunveriler',
            name='sorun_tipi',
            field=models.CharField(choices=[('Hijyen', 'Hijyen'), ('Ürün Kalitesi', 'Ürün Kalitesi'), ('İnsan Sağlığı', 'İnsan Sağlığı'), ('Hizmet Kalitesi', 'Hizmet Kalitesi')], default='Hizmet Kalitesi', max_length=50),
        ),
    ]
