# Generated by Django 4.2.7 on 2025-04-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_gonullusorunveriler_sorun_seviyesi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonullusorunveriler',
            name='sorun_seviyesi',
            field=models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Acil', 'Acil')], default='Düşük', max_length=20),
        ),
        migrations.AlterField(
            model_name='gonullusorunveriler',
            name='sorun_tipi',
            field=models.CharField(choices=[('Hijyen', 'Hijyen'), ('Ürün Kalitesi', 'Ürün Kalitesi'), ('İnsan Sağlığı', 'İnsan Sağlığı'), ('Hizmet Kalitesi', 'Hizmet Kalitesi')], default='Hizmet Kalitesi', max_length=50),
        ),
        migrations.CreateModel(
            name='GonulluDurumFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('durum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='forms.gonulludurumveriler')),
            ],
            options={
                'verbose_name': 'Gönüllü Durum Fotoğrafı',
                'verbose_name_plural': 'Gönüllü Durum Fotoğrafları',
                'db_table': 'gonullu_durum_fotograflar',
            },
        ),
    ]
