# Generated by Django 4.2.7 on 2025-04-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_gonullusorunveriler_sorun_seviyesi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GonulluSorunFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('sorun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='forms.gonullusorunveriler')),
            ],
            options={
                'verbose_name': 'Gönüllü Sorun Fotoğrafı',
                'verbose_name_plural': 'Gönüllü Sorun Fotoğrafları',
                'db_table': 'gonullu_sorun_fotograflar',
            },
        ),
    ]
