# Generated by Django 5.1.6 on 2025-09-24 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_gonulludurumveriler_aciklama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YeniKelime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=100, verbose_name='İngilizce Kelime')),
                ('anlam', models.CharField(blank=True, max_length=200, null=True, verbose_name='Türkçe Anlamı')),
                ('cumle', models.TextField(blank=True, null=True, verbose_name='Örnek Cümle')),
                ('ogrenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Öğrenme Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeni_kelimeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yeni Kelime',
                'verbose_name_plural': 'Yeni Kelimeler',
                'db_table': 'yeni_kelimeler',
                'ordering': ['-ogrenme_tarihi'],
            },
        ),
    ]
